[package]
name        = "vledger-wal"
description = "Append-only Write-Ahead Log with crash recovery and fsync durability"
version.workspace     = true
edition.workspace     = true
authors.workspace     = true
license.workspace     = true
repository.workspace  = true

[dependencies]
vledger-crypto = { workspace = true }
serde          = { workspace = true }
bincode        = { workspace = true }
thiserror      = { workspace = true }
tracing        = { workspace = true }
chrono         = { workspace = true }
uuid           = { workspace = true }
crc32fast      = { workspace = true }
tokio          = { workspace = true }
tokio-util     = { workspace = true }
aes-gcm        = { workspace = true }
hkdf           = { workspace = true }
sha2           = { workspace = true }
rand           = { workspace = true }
rand_core      = { workspace = true }
ed25519-dalek  = { workspace = true }
hex            = { workspace = true }

[dev-dependencies]
tempfile = "3.20.0"
proptest = { workspace = true }
